// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refreshtokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refreshtokens (token, 
created_at,
updated_at,
user_id,
expires_at) VALUES($1, $2, $3, $4, $5)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (Refreshtoken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i Refreshtoken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefTokByID = `-- name: GetRefTokByID :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refreshtokens WHERE token=$1 AND revoked_at IS NULL
`

func (q *Queries) GetRefTokByID(ctx context.Context, token string) (Refreshtoken, error) {
	row := q.db.QueryRowContext(ctx, getRefTokByID, token)
	var i Refreshtoken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefTok = `-- name: RevokeRefTok :exec
UPDATE refreshtokens
SET updated_at=$2, revoked_at=$2
WHERE token=$1
AND revoked_at IS NULL
AND expires_at>NOW()
`

type RevokeRefTokParams struct {
	Token     string    `json:"token"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) RevokeRefTok(ctx context.Context, arg RevokeRefTokParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefTok, arg.Token, arg.UpdatedAt)
	return err
}
